language: rust
rust: nightly
cache: cargo
sudo: false

addons:
  firefox: latest
  chrome : stable

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

before_script:
  - rustup target add wasm32-unknown-unknown

script:

  # this will test the non wasm targets if your crate has those, otherwise remove this line.
  #
  - cargo test
  - wasm-pack test --node
  - wasm-pack test --firefox --headless
  - wasm-pack test --chrome  --headless
